#!/usr/bin/env ruby
 
require 'mcollective'

include MCollective::RPC
 
options = rpcoptions do |parser, options|
    parser.define_head "Mcollective virsh-like tool"
    parser.banner = "Usage: mc-virsh [options] [filters] --all"

    parser.on('-a', '--all', 'Operate on all domains where appropriate (eg: list)') do |v|
       options[:all] = true
    end
end

if ARGV.length == 1
    actions = ['list', 'status']
    action = ARGV.shift
    unless actions.index(action)
        puts("Action must be one of " + actions.join(', '))
        exit 1
    end
else
    puts("Please specify an action")
    exit 1
end

mc = rpcclient("mclibvirt", :options => options)
mc.progress = false

case action
    when "list"
        mc.list(:all => options[:all]).each do |resp|
        puts resp[:sender] + ':'
        puts "\t" + resp[:data].sort.join("\n\t")
    end
end

mc.disconnect
